// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHW5bnJjyc56Rxq3tdeV9FNkSOHWO0bK4',
    appId: '1:269583027558:android:cb43ec3dfd0728ef59cca7',
    messagingSenderId: '269583027558',
    projectId: 'mobileprogrammingproject-bd318',
    storageBucket: 'mobileprogrammingproject-bd318.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHW5bnJjyc56Rxq3tdeV9FNkSOHWO0bK4',
    appId: '1:269583027558:ios:cb43ec3dfd0728ef59cca7',
    messagingSenderId: '269583027558',
    projectId: 'mobileprogrammingproject-bd318',
    storageBucket: 'mobileprogrammingproject-bd318.firebasestorage.app',
    iosBundleId: 'com.example.smartCampusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHW5bnJjyc56Rxq3tdeV9FNkSOHWO0bK4',
    appId: '1:269583027558:ios:cb43ec3dfd0728ef59cca7',
    messagingSenderId: '269583027558',
    projectId: 'mobileprogrammingproject-bd318',
    storageBucket: 'mobileprogrammingproject-bd318.firebasestorage.app',
    iosBundleId: 'com.example.smartCampusApp',
  );
}

